#!/usr/bin/env bash

echo "Copying installer scripts to target..."
BASH_DIR="$(dirname "$(readlink -f "$0")")"

mkdir -p /mnt/usr/local/bin
if cp -r "$BASH_DIR/"* /mnt/usr/local/bin/ && chmod +x /mnt/usr/local/bin/*; then
    echo "Scripts copied successfully."
else 
    echo "Error: Failed to copy scripts."
    exit 1
fi