#!/usr/bin/env bash

echo "Defining target device..."

# List disks and prompt
BASE_DIR="/usr/local/share"
VARS_FILE="$BASE_DIR/disk.sh"

if [[ ! -f "$VARS_FILE" ]]; then
  echo "Missing vars file: $VARS_FILE" >&2
  exit 1
fi
source "$VARS_FILE"


echo "Creating partition table..."
parted -s "$TARGET_DISK" mklabel gpt || { echo "Faild to create partition table"; exit 1; }
echo "Success."

echo "Creating UEFI Boot Partition (1GiB)..."
parted -s "$TARGET_DISK" mkpart primary fat32 1MiB 1025MiB || { echo "Faild to create UEFI boot partition."; exit 1; }
parted -s "$TARGET_DISK" set 1 esp on || { echo "Faild to create UEFI boot partition."; exit 1; }
echo "Success."

rootstart=1025

# rootsize=${rootsize:-10000}
rootsize=10000

while [ "$rootsize" -lt 10000 ]; do
    echo "Error: $rootsize is too small. Minimum is 10000."
    #read -p "Define size of root partition: " rootsize
    #rootsize=${rootsize:-10000}
done

echo "Creating root partition ($rootsize)..."
rootend=$((rootstart + rootsize))
parted -s "$TARGET_DISK" mkpart primary ext4 "${rootstart}MiB" "${rootend}MiB"
echo "Success."

#read -p "Create swap partition? Y/n? " swapyn
swapyn="y"
swapyn=${swapyn:-"y"}

if [ "$swapyn" == "y" ]; then
    while [ -z "$swapsize" ]; do
        read -p "Define size of swap partition. (In MiB, Minimum 1000) " swapsize
    done

    echo "Creating Swap Partition ($swapsize)..."
    parted -s "$TARGET_DISK" mkpart primary linux-swap "${rootend}MiB" "$((rootend + swapsize))MiB"
    echo "Success."
fi

echo "Successfully created UEFI, root and swap partition."

export swapyn
export swapsize
export rootsize

ENV_FILE="/tmp/partition.env"
cat > "$ENV_FILE" <<EOF
export DISK="$TARGET_DISK"
export rootsize="$rootsize"
export swapsize="$swapsize"
export swapyn="$swapyn"
EOF
