#!/usr/bin/env bash

echo "Defining target device..."

# List disks and prompt
BASE_DIR="/usr/local/share"
VARS_FILE="$BASE_DIR/disk.sh"

if [[ ! -f "$VARS_FILE" ]]; then
  echo "Missing vars file: $VARS_FILE" >&2
  exit 1
fi
source "$VARS_FILE"


echo "Creating partition table..."
parted -s "$TARGET_DISK" mklabel gpt || { echo "Faild to create partition table"; exit 1; }
echo "Success."

echo "Creating UEFI Boot Partition (1GiB)..."
parted -s "$TARGET_DISK" mkpart primary fat32 1MiB 1025MiB || { echo "Faild to create UEFI boot partition."; exit 1; }
parted -s "$TARGET_DISK" set 1 esp on || { echo "Faild to create UEFI boot partition."; exit 1; }
echo "Success."

rootstart=1025


echo "Creating root partition ($rootsize)..."
rootend=$((rootstart + rootsize))
parted -s "$TARGET_DISK" mkpart primary ext4 "${rootstart}MiB" "${rootend}MiB"
echo "Success."


if [ "$swapyn" == "y" ]; then
    echo "Creating Swap Partition ($swapsize)..."
    parted -s "$TARGET_DISK" mkpart primary linux-swap "${rootend}MiB" "$((rootend + swapsize))MiB"
    echo "Success."
fi

echo "Successfully created UEFI, root and swap partition."

export swapyn
export swapsize
export rootsize

ENV_FILE="/tmp/partition.env"
cat > "$ENV_FILE" <<EOF
export DISK="$TARGET_DISK"
export rootsize="$rootsize"
export swapsize="$swapsize"
export swapyn="$swapyn"
EOF
